name: forekast_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  adaptive_theme: ^3.6.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
